- name: "Ensure {{ item }}.service in place for systemd to use"
  template:
    src: "{{ item }}.service.j2"
    dest: "/etc/systemd/system/{{ item }}.service"
    backup: true
    mode: 0644
  become: true
  loop: "{{ chrono_index_services }}"

- name: "Ensure {{ item }}.service is enabled"
  ansible.builtin.systemd_service:
    state: started
    # Reload systemd daemon to apply changes to services.
    daemon_reload: true
    enabled: true
    name: "{{ item }}"
  become: true
  loop: "{{ chrono_index_services }}"
