- name: Ensure info_field_chrono_index.service in place for systemd to use
  template:
    src: info_field_chrono_index.service.j2
    dest: "/etc/systemd/system/info_field_chrono_index.service"
    backup: true
    mode: 0644
  become: true

- name: Ensure info_field_chrono_index.service is enabled
  ansible.builtin.systemd_service:
    state: started
    # Reload systemd daemon to apply changes to services.
    daemon_reload: true
    enabled: true
    name: info_field_chrono_index
  become: true


