- include_tasks: ensure_keyszer_runs_from_keymapper.yml

# Unfortunately, doesn't work: keymapper can't access file in dest. It seems not
# as a problem with permissions but with keyszer functionality. I checked:
# access is ok but keyszer can't read file. Most likely a symlink issue.
# - name: Symlink Keyszer scripts
#   vars:
#     system_scripts: /home/ds13/.bookmarks/system-scripts
#   ansible.builtin.file:
#     src: "{{ system_scripts }}/Keymappings__Keyszer_scripts/keyszer.conf"
#     dest: "{{ keyszer_config_path }}"
#     group: wheel
#     # Ensure keymapper has access to the file
#     mode: o=rx
#     state: hard
#   become: true


- name: Copy Keyszer scripts
  vars:
    system_scripts: /home/ds13/.bookmarks/system-scripts
  ansible.builtin.copy:
    src: "{{ system_scripts }}/Keymappings__Keyszer_scripts/keyszer.conf"
    dest: "{{ keyszer_config_path }}"
    group: wheel
    # Ensure keymapper has access to the file
    mode: o=rx
  become: true
  
# TODO: Add `yay xkblayout-state-git`
