# Throws error 'Not a windows host'. Most likely because Windows host is targeted via bridge from VM.
# - name: Enable needed features
#   ansible.windows.win_feature:
#     name:
#       - VirtualMachinePlatform
#       - Microsoft-Windows-Subsystem-Linux
#     state: present

# Had some errors previous time… While executing it manually was ok.
- name: Set up WSL Distribution NixOS 
  ansible.windows.win_powershell:
      script: |
        [CmdletBinding()]
        param (
            [String]
            $DistributivePath,

            [String]
            $InstallationPath,

            [String]
            $WslVersion,

            [String]
            $DistributionName
        )

        mkdir -Force "$InstallationPath"

        if (-Not (Test-Path "$InstallationPath")) {
          echo "InstallationPath doesn't exist: $InstallationPath"

          return 1
        }

        if (-Not (Test-Path "$DistributivePath")) {
          echo "DistributivePath doesn't exist: $DistributivePath"

          return 1
        }

        wsl --import "$DistributionName" "$InstallationPath" "$DistributivePath" --version [int]"$WslVersion"
      parameters:
        DistributivePath: "{{ distributive_path }}"
        InstallationPath: "{{ installation_path }}"
        WslVersion: "{{ wsl_version }}"
        DistributionName: "{{ distribution_name }}"
  when: '"Windows" in ansible_distribution'

- name: Make installed distribution default
  ansible.windows.win_powershell:
      script: |
        [CmdletBinding()]
        param (
            [String]
            $DistributionName
        )

        wsl --set-default "$DistributionName"
      parameters:
        DistributionName: "{{ distribution_name }}"
  when: '"Windows" in ansible_distribution'

# https://nix-community.github.io/NixOS-WSL/install.html
# Post-install
# update channels
# nix-shell -p git
# fetch flake
# sudo nixos-rebuild switch --flake . --impure
# assign passwords: `sudo -i`, `sudo passwd <user>`
# change permissions for configuration folder: `chown -R :wheel <path>`, `chmod
# g+w -R <path>`
# or maybe easier to package own system https://nix-community.github.io/NixOS-WSL/building.html

