- name: Set up local workstation (general)
  hosts: all
  roles:
      # Text Editor.
    - role: neovim
      tags:
        - neovim

      # - Git TUI.
    - role: lazygit
      tags:
        - git
        - lazygit
        - development

- name: Prepare local UNIX workstation for nix setup
  hosts: salt
  roles:
    - role: nix
      tags:
        - nix

    - role: nix-homemanager
      tags:
        - nix-homemanager

    - role: pipx

    - role: keyszer
      tags:
        - keymapper
        - keyszer

    - role: invoke
      tags:
        - scripting
        - invoke

- name: Set up inside Virtual Machine
  hosts: pepper
  roles:
    - role: samba_mounts
      tags:
        - samba_mounts

- name: Set up local Windows workstation
  hosts: windows
  roles:
    - role: samba
      tags:
        - samba

    - role: vivaldi
      tags:
        - vivaldi
        - browser

    - role: wsl_nixos
      tags:
        - wsl_nixos
        - wsl
        - nix

      # Git
    # - role: git
    #   tags:
    #     - git
    - role: fonts
      tags:
        - fonts
        - Iosevka

    - role: latex
      tags:
        - latex
        - writing

    - role: wezterm
      tags:
        - wezterm
        - development

    - role: powershell
      tags:
        - development
        - powershell

    - role: scoop
      tags:
        - scoop
    - role: oh_my_posh
      tags:
        - powershell

      # Productivity.
    - role: bugwarrior
      tags:
        - bugwarrior
        - jira # TODO: Modularize it somehow?
        - productivity
      when: '"Windows" not in ansible_distribution' # Taskwarrior not supported on windows.

      # Pdf.
      # - Pdf Reader
    - role: sumatrapdf
      tags:
        - pdf
        - sumatrapdf

      # Development.
      # - Golang
    - role: golang
      tags:
        - golang
        - backend
        - development

      # - Python
    - role: python
      tags:
        - python
        - backend
        - machine_learning
        - development

    # - role: snap
    #   tags:
    #     - snap
    # - role: zsh
    #   tags:
    #     - zsh
    # - role: fzf
    #   tags:
    #     - fzf
    # - role: vim
    #   tags:
    #     - vim
    # - role: tmux
    #   tags:
    #     - tmux
    # - role: asdf
    #   tags:
    #     - asdf
    # - role: python
    #   tags:
    #     - python
    # - role: terraform
    #   tags:
    #     - terraform
    # - role: golang
    #   tags:
    #     - golang
    # - role: ruby
    #   tags:
    #     - ruby
    # - role: erlang
    #   tags:
    #     - erlang
    # - role: elixir
    #   tags:
    #     - elixir
    # - role: node
    #   tags:
    #     - node
    # - role: redis
    #   tags:
    #     - redis
    - role: ripgrep_all
      tags:
        - ripgrep

