# Setting up workstations for personal use.
- name: Set up local workstation (general)
  hosts: all
  roles:
      # Text Editor.
    - role: neovim
      tags:
        - neovim

      # - Git TUI.
    - role: lazygit
      tags:
        - git
        - lazygit
        - development

    - role: pipx
      tags:
        - pipx

    - role: invoke
      tags:
        - scripting
        - invoke

      # InfoField.
    - role: info_field_chrono_index
      tags:
        - info_field_chrono_index


- name: Set up local Unix workstation (general)
  hosts:
    - salt
    - creamsoda
  roles:
    - role: manly
      tags:
        - knowledge
        - manly


- name: Prepare local Unix workstation for nix setup
  hosts:
    - salt
    - creamsoda
  roles:
    - role: nix
      tags:
        - nix

    - role: nix-homemanager
      tags:
        - nix-homemanager


- name: Set up local ArchLinux workstation
  hosts: salt
  roles:
    - role: partitions
      tags:
        - partitions

    - role: filesystem
      tags:
        - filesystem

    - role: docker
      tags:
        - development
        - devops
        - docker

    - role: keyszer
      tags:
        - keymapper
        - keyszer


- name: Set up local MacOs workstation
  hosts: creamsoda
  roles:
    # ? Move to general?
    - role: vivaldi
      tags:
        - vivaldi
        - browser


- name: Set up inside Virtual Machine
  hosts: pepper
  roles:
    - role: samba_mounts
      tags:
        - samba_mounts


- name: Set up local Windows workstation
  hosts: windows
  roles:
    - role: samba
      tags:
        - samba

    - role: vivaldi
      tags:
        - vivaldi
        - browser

    - role: logseq
      tags:
        - logseq
        - productivity

    - role: bat
      tags:
        - bat

    - role: wsl_nixos
      tags:
        - wsl_nixos
        - wsl
        - nix

      # Git
    # - role: git
    #   tags:
    #     - git
    - role: fonts
      tags:
        - fonts
        - Iosevka

    - role: latex
      tags:
        - latex
        - writing

    - role: wezterm
      tags:
        - wezterm
        - development

    - role: powershell
      tags:
        - development
        - powershell

    - role: scoop
      tags:
        - scoop

    - role: oh_my_posh
      tags:
        - powershell

      # Productivity.
    - role: bugwarrior
      tags:
        - bugwarrior
        - jira # TODO: Modularize it somehow?
        - productivity
      when: '"Windows" not in ansible_distribution' # Taskwarrior not supported on windows.

      # Pdf.
      # - Pdf Reader
    - role: sumatrapdf
      tags:
        - pdf
        - sumatrapdf

      # Development.
    - role: docker
      tags:
        - development
        - devops
        - docker
      # - Golang
    - role: golang
      tags:
        - golang
        - backend
        - development

      # - Python
    - role: python
      tags:
        - python
        - backend
        - machine_learning
        - development

    # - role: snap
    #   tags:
    #     - snap
    # - role: zsh
    #   tags:
    #     - zsh
    # - role: fzf
    #   tags:
    #     - fzf
    # - role: vim
    #   tags:
    #     - vim
    # - role: tmux
    #   tags:
    #     - tmux
    # - role: asdf
    #   tags:
    #     - asdf
    # - role: python
    #   tags:
    #     - python
    # - role: terraform
    #   tags:
    #     - terraform
    # - role: golang
    #   tags:
    #     - golang
    # - role: ruby
    #   tags:
    #     - ruby
    # - role: erlang
    #   tags:
    #     - erlang
    # - role: elixir
    #   tags:
    #     - elixir
    # - role: node
    #   tags:
    #     - node
    # - role: redis
    #   tags:
    #     - redis
    - role: ripgrep_all
      tags:
        - ripgrep

- name: Set up lent workstation MikhailLermontov
  hosts: MikhailLermontov
  roles:
    - role: users
      tags:
        - users


