- name: Set up local workstation
  hosts: windows
  roles:
      # Git
    # - role: git
    #   tags:
    #     - git

      # Productivity.
    - role: bugwarrior
      tags:
        - bugwarrior
        - jira # TODO: Modularize it somehow?
        - productivity
      when: '"Windows" not in ansible_distribution' # Taskwarrior not supported on windows.

      # - Git TUI.
    - role: lazygit
      tags:
        - git
        - lazygit
        - development

      # Text Editor.
    - role: neovim
      tags:
        - neovim

      # Pdf.
      # - Pdf Reader
    - role: sumatrapdf
      tags:
        - pdf
        - sumatrapdf

      # Backend Development.
      # - Golang
    - role: golang
      tags:
        - golang
        - backend
          development

    # - role: snap
    #   tags:
    #     - snap
    # - role: zsh
    #   tags:
    #     - zsh
    # - role: fzf
    #   tags:
    #     - fzf
    # - role: vim
    #   tags:
    #     - vim
    # - role: tmux
    #   tags:
    #     - tmux
    # - role: asdf
    #   tags:
    #     - asdf
    # - role: python
    #   tags:
    #     - python
    # - role: terraform
    #   tags:
    #     - terraform
    # - role: golang
    #   tags:
    #     - golang
    # - role: ruby
    #   tags:
    #     - ruby
    # - role: erlang
    #   tags:
    #     - erlang
    # - role: elixir
    #   tags:
    #     - elixir
    # - role: node
    #   tags:
    #     - node
    # - role: redis
    #   tags:
    #     - redis
    - role: ripgrep_all
      tags:
        - ripgrep

