- name: Set up local workstation
  hosts: windows
  roles:
    - role: ripgrep_all
      tags:
        - ripgrep
    # - role: git
    #   tags:
    #     - git
    # - Git TUI.
    - role: lazygit
      tags:
        - git
    # - role: snap
    #   tags:
    #     - snap
    # - role: zsh
    #   tags:
    #     - zsh
    # - role: fzf
    #   tags:
    #     - fzf
    # - role: vim
    #   tags:
    #     - vim
    # - role: tmux
    #   tags:
    #     - tmux
    # - role: asdf
    #   tags:
    #     - asdf
    # - role: python
    #   tags:
    #     - python
    # - role: terraform
    #   tags:
    #     - terraform
    # - role: golang
    #   tags:
    #     - golang
    # - role: ruby
    #   tags:
    #     - ruby
    # - role: erlang
    #   tags:
    #     - erlang
    # - role: elixir
    #   tags:
    #     - elixir
    # - role: node
    #   tags:
    #     - node
    # - role: redis
    #   tags:
    #     - redis
