#   Can be installed via python too but pacman will cry that he is better. Not
# gonna argue :)
- name: Install package pipx via pacman
  community.general.pacman:
    name: python-pipx
  when: ansible_facts['os_family'] == 'Archlinux'

- name: Install package pipx via brew
  community.general.homebrew:
    name: pipx
  when: ansible_facts['os_family'] == 'Darwin'

- name: Install pipx via scoop (on Windows)
  community.windows.win_scoop:
    name: pipx
  when: '"Windows" in ansible_distribution'

  # TODO: Filter out Windows too.
- name: Install pipx via pip
  ansible.builtin.pip:
    name: pipx
    extra_args: --user
  when: not ansible_facts['os_family'] == 'Archlinux' and not ansible_facts['os_family'] == 'Darwin'
