---
# ansible_user: ds13
# ansible_password: "{{ vault_windows_ds13_password }}"
# ansible_port: 5986
# ansible_connection: winrm
# ansible_winrm_transport: basic
# ansible_winrm_server_cert_validation: ignore
ansible_user: ds13
ansible_password: "{{ vault_windows_ds13_password }}"
ansible_shell_type: powershell
# ansible_port: 5986
# ansible_connection: winrm
# ansible_winrm_transport: basic
# ansible_winrw_server_cert_validation: ignore

# I prefer this way more but it doesn't work without Powershell environment.
# configs_root: "J:/$Env:UserName/Soft/-scoop"
# This requires that ansible_user == user that we deploy to.
configs_root: "J:/{{ ansible_user }}/Soft/-scoop"
scripts_root: "H:/Scripts"
shims_root: "{{ configs_root }}/shims"
global_scoop_apps_root: "J:/Soft/-scoop"
ansible_user_home: "C:/Users/{{ ansible_user }}"
shared_root: "H:/Shared"
shared_scripts_root: "{{ shared_root }}/_scripts"
system_configs_root: "{{ ansible_user_home }}/AppData/Roaming"
...
