- name: Install Powershell (on Windows)
  community.windows.win_scoop:
    name: pwsh
  when: '"Windows" in ansible_distribution'

- name: Symlink Powershell configuration (on Windows)
  vars:
    force: true
  ansible.windows.win_powershell:
      script: |
        [CmdletBinding()]
        param (
            [String]
            $Path,

            [Switch]
            $Force
        )

        # New-Item -ItemType SymbolicLink -Value "H:/Configs/Powershell" -Path "$(Split-Path $($Env:PSModulePath.split(';')[0]))" -Force:$Force
        New-Item -ItemType SymbolicLink -Value "H:/Configs/Powershell_config" -Path "$Env:UserProfile/Documents/Powershell" -Force:$Force
      parameters:
        Force: "{{ force }}"
  when: '"Windows" in ansible_distribution'

- import_tasks: terminal-icons.yaml

