# These tasks may cause issues when updating system packages
# (xkeyboard-config) as it checks for foreign files in /usr/share/X11/xkb.
# Check for solution: logseq://graph/Notes?block-id=68809b1f-3f36-4ccc-8cf7-ad3ad99e7ee7

- name: Copy symbols layout
  ansible.builtin.copy:
    src: "{{x11_local_system_configs}}/Keyboard__HdnExtended_xorgLayout/{{x11_layout_name}}"
    dest: "/usr/share/X11/xkb/symbols/{{x11_layout_name}}"
  become: true

- name: Copy X11 (xorg.conf.d) settings
  ansible.builtin.copy:
    src: "{{x11_local_system_configs}}/xorg.conf.d"
    dest: "/etc/X11/"
  become: true

- name: Copy xinit settings
  ansible.builtin.copy:
    src: "{{x11_local_system_configs}}/xorg.conf.d"
    dest: "/etc/X11/"
  become: true

- name: Ensure .xinit settings are place
  template:
    src: .xinit.j2
    dest: "/home/{{ansible_user}}/.xinit"
    mode: 0554
