- name: Install Oh My Posh (on Windows)
  community.windows.win_scoop:
    name: https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/oh-my-posh.json
  when: '"Windows" in ansible_distribution'
