# Reference: https://docs.docker.com/engine/security/rootless/#distribution-specific-hint

- name: Install docker (on Windows)
  community.windows.win_scoop:
    name: docker-desktop
  when: '"Windows" in ansible_distribution'

- include_tasks: enable_rootless_mode.yml
  when: '"Archlinux" in ansible_distribution'
