- name: Install NeoVim (on Windows)
  community.windows.win_scoop:
    name: neovim
  when: '"Windows" in ansible_distribution'

# Throws some python error...
# - name: Clone a NeoVim_config repo with separate git directory on a host
  # ansible.builtin.git:
    # repo: git@github.com:DeadlySquad13/NeoVim_config.git
    # repo: https://github.com/sqlite/sqlite.git
    # dest: "C:/Users/ds13/.bookmarks/Projects/--personal/Programming_dotfiles.bootstrap/roles/neovim/files"
    # dest: /home/ds13/projects/shared-/--personal/Programming_dotfiles.bootstrap/roles/neovim/files
    # dest: /home/ds13/projects/test

- name: Symlink NeoVim configuration (on Windows)
  vars:
    force: true
  ansible.windows.win_powershell:
      script: |
        [CmdletBinding()]
        param (
            [String]
            $Path,

            [Switch]
            $Force
        )

        New-Item -ItemType SymbolicLink -Value "C:/Users/ds13/.bookmarks/Projects/--personal/Programming_dotfiles.bootstrap/roles/neovim/files" -Path "$Env:LocalAppData/nvim" -Force:$Force
      parameters:
        Force: "{{ force }}"
  when: '"Windows" in ansible_distribution'

# About C Compilers on Windows: https://github.com/nvim-treesitter/nvim-treesitter/wiki/Windows-support#zig
# About Zig: https://andrewkelley.me/post/zig-cc-powerful-drop-in-replacement-gcc-clang.html
- name: Install C Compiler Zig for NeoVim (on Windows)
  community.windows.win_scoop:
    name: zig
  when: '"Windows" in ansible_distribution'

- name: Install Gui NeoVim (on Windows)
  community.windows.win_scoop:
    name: neovide
  when: '"Windows" in ansible_distribution'

- name: Make Gui NeoVim default for text-based filetypes (on Windows)
  vars:
    neovim_gui_path: J:/ds13/Soft/-scoop/shims/neovide.exe
  ansible.windows.win_powershell:
      script: |
        [CmdletBinding()]
        param (
            [String]
            $NeovimGuiPath
        )

        cmd /c ftype txtfile="$NeovimGuiPath" "%1"
      parameters:
        NeovimGuiPath: "{{ neovim_gui_path }}"
  when: '"Windows" in ansible_distribution'
