# For full list see: https://github.com/g2g/ansible-role-taskd/blob/master/defaults/main.yml
# Organizations to be created
# TODO: Better do it via `/dev/disk/by-id` or any other way instead of using
# block devices directly.
zfs_pool_vdevs:
  - /dev/sdd4
  - /dev/nvme2n1
